services:
    prometheus:
        image: docker.io/prom/prometheus:v3.8.1
        container_name: prometheus
        command: [ 
            "--config.file=/etc/prometheus/prometheus.yml",
            "--web.enable-otlp-receiver"
        ]
        volumes:
            - prometheus-data:/prometheus
            - ./configurations/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
        ports:
            - 9090:9090
volumes:
    prometheus-data: